//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1318
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BdsSoft.SharePoint.Linq {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BdsSoft.SharePoint.Linq.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t negate a {0} query expression..
        /// </summary>
        internal static string CantNegate {
            get {
                return ResourceManager.GetString("CantNegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A call to DateRangesOverlap should not have an entity property reference as its value argument..
        /// </summary>
        internal static string DateRangesOverlapInvalidValueArgument {
            get {
                return ResourceManager.GetString("DateRangesOverlapInvalidValueArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A call to DateRangesOverlap should have one or more field references in its fields argument..
        /// </summary>
        internal static string DateRangesOverlapMissingFieldReferences {
            get {
                return ResourceManager.GetString("DateRangesOverlapMissingFieldReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred in the predicate parser..
        /// </summary>
        internal static string FatalError {
            get {
                return ResourceManager.GetString("FatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query predicate contains an entity reference that doesn&apos;t belong to a SharePoint list context: {0}..
        /// </summary>
        internal static string InvalidEntityReference {
            get {
                return ResourceManager.GetString("InvalidEntityReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-boolean constant values are not supported in query predicates..
        /// </summary>
        internal static string NonBoolConstantValueInPredicate {
            get {
                return ResourceManager.GetString("NonBoolConstantValueInPredicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t add another predicate expression to the query..
        /// </summary>
        internal static string PredicateAfterProjection {
            get {
                return ResourceManager.GetString("PredicateAfterProjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query predicate contains a method call on a non-entity property: {0}..
        /// </summary>
        internal static string PredicateContainsNonEntityMethodCall {
            get {
                return ResourceManager.GetString("PredicateContainsNonEntityMethodCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query predicate contains a non-entity property reference: {0}..
        /// </summary>
        internal static string PredicateContainsNonEntityReference {
            get {
                return ResourceManager.GetString("PredicateContainsNonEntityReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported method call detected in query predicate: {0}..
        /// </summary>
        internal static string UnsupportedMethodCall {
            get {
                return ResourceManager.GetString("UnsupportedMethodCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query operator {0} is not supported..
        /// </summary>
        internal static string UnsupportedQueryOperator {
            get {
                return ResourceManager.GetString("UnsupportedQueryOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported string filtering query expression detected: {0}. Only the methods Contains and StartsWith are supported..
        /// </summary>
        internal static string UnsupportedStringMethodCall {
            get {
                return ResourceManager.GetString("UnsupportedStringMethodCall", resourceCulture);
            }
        }
    }
}
